# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/usr/local/Ncsis_Docker_Recovery/recovery.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(837, 815)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../home/uscc/Downloads/logo-only.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_coninfoT = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_coninfoT.setFont(font)
        self.label_coninfoT.setObjectName("label_coninfoT")
        self.verticalLayout_2.addWidget(self.label_coninfoT)
        self.textBrowser_coninfoC = QtWidgets.QTextBrowser(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_coninfoC.sizePolicy().hasHeightForWidth())
        self.textBrowser_coninfoC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textBrowser_coninfoC.setFont(font)
        self.textBrowser_coninfoC.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textBrowser_coninfoC.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textBrowser_coninfoC.setToolTip("")
        self.textBrowser_coninfoC.setAutoFillBackground(False)
        self.textBrowser_coninfoC.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_coninfoC.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_coninfoC.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_coninfoC.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser_coninfoC.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser_coninfoC.setCursorWidth(1)
        self.textBrowser_coninfoC.setObjectName("textBrowser_coninfoC")
        self.verticalLayout_2.addWidget(self.textBrowser_coninfoC)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_conidT = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_conidT.setFont(font)
        self.label_conidT.setObjectName("label_conidT")
        self.horizontalLayout.addWidget(self.label_conidT)
        self.lineEdit_conidC = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_conidC.setFont(font)
        self.lineEdit_conidC.setText("")
        self.lineEdit_conidC.setObjectName("lineEdit_conidC")
        self.horizontalLayout.addWidget(self.lineEdit_conidC)
        self.pushButton_search = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setCheckable(True)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.verticalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_backupinfoT = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_backupinfoT.setFont(font)
        self.label_backupinfoT.setAutoFillBackground(False)
        self.label_backupinfoT.setObjectName("label_backupinfoT")
        self.verticalLayout_3.addWidget(self.label_backupinfoT)
        self.textBrowser_backupinfoC = QtWidgets.QTextBrowser(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_backupinfoC.sizePolicy().hasHeightForWidth())
        self.textBrowser_backupinfoC.setSizePolicy(sizePolicy)
        self.textBrowser_backupinfoC.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.textBrowser_backupinfoC.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.textBrowser_backupinfoC.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser_backupinfoC.setObjectName("textBrowser_backupinfoC")
        self.verticalLayout_3.addWidget(self.textBrowser_backupinfoC)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(Dialog)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_recoveryT = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_recoveryT.setFont(font)
        self.label_recoveryT.setObjectName("label_recoveryT")
        self.horizontalLayout_2.addWidget(self.label_recoveryT)
        self.lineEdit_recoveryC = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_recoveryC.setFont(font)
        self.lineEdit_recoveryC.setText("")
        self.lineEdit_recoveryC.setObjectName("lineEdit_recoveryC")
        self.horizontalLayout_2.addWidget(self.lineEdit_recoveryC)
        self.pushButton_backup = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_backup.setFont(font)
        self.pushButton_backup.setCheckable(True)
        self.pushButton_backup.setObjectName("pushButton_backup")
        self.horizontalLayout_2.addWidget(self.pushButton_backup)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_result = QtWidgets.QLabel(self.widget_5)
        self.label_result.setMaximumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_3.addWidget(self.label_result)
        self.textBrowser_result = QtWidgets.QTextBrowser(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_result.sizePolicy().hasHeightForWidth())
        self.textBrowser_result.setSizePolicy(sizePolicy)
        self.textBrowser_result.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_result.setFont(font)
        self.textBrowser_result.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.textBrowser_result.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.textBrowser_result.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textBrowser_result.setObjectName("textBrowser_result")
        self.horizontalLayout_3.addWidget(self.textBrowser_result)
        self.verticalLayout.addWidget(self.widget_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Docker Recovery"))
        self.label_coninfoT.setText(_translate("Dialog", "運行的容器資訊 :"))
        self.label_conidT.setText(_translate("Dialog", "輸入需復原的容器ID : "))
        self.pushButton_search.setText(_translate("Dialog", "查詢可復原的備份資料"))
        self.label_backupinfoT.setText(_translate("Dialog", "可復原的備份資訊 :"))
        self.label_recoveryT.setText(_translate("Dialog", "輸入要復原到的容器狀態 : "))
        self.pushButton_backup.setText(_translate("Dialog", "進行還原"))
        self.label_result.setText(_translate("Dialog", "運行結果 :"))


